// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDid3fbcHJ5Y-BtLIDSEbE4C6eAljPVdzg',
    appId: '1:645333407510:web:1f2b90253295cfe24de237',
    messagingSenderId: '645333407510',
    projectId: 'studentmanagemnetweb',
    authDomain: 'studentmanagemnetweb.firebaseapp.com',
    storageBucket: 'studentmanagemnetweb.appspot.com',
    measurementId: 'G-6RMMREFQ7T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAJ1lQhsE2ymwU4iPRA50CNloL4GfOpc4',
    appId: '1:645333407510:android:f1892c7977d65dbe4de237',
    messagingSenderId: '645333407510',
    projectId: 'studentmanagemnetweb',
    storageBucket: 'studentmanagemnetweb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC6yZzJehtkBtswzu13d-U5rngzJ47nsk',
    appId: '1:645333407510:ios:e1da501a890025fb4de237',
    messagingSenderId: '645333407510',
    projectId: 'studentmanagemnetweb',
    storageBucket: 'studentmanagemnetweb.appspot.com',
    iosBundleId: 'com.example.studentManagementWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC6yZzJehtkBtswzu13d-U5rngzJ47nsk',
    appId: '1:645333407510:ios:5ddd64a95e243d024de237',
    messagingSenderId: '645333407510',
    projectId: 'studentmanagemnetweb',
    storageBucket: 'studentmanagemnetweb.appspot.com',
    iosBundleId: 'com.example.studentManagementWeb.RunnerTests',
  );
}
